g4math.complete = dataCleanup(g4math.complete)
overall.results = data.frame()

g4math.lr = glm(g4formula, data=g4math.complete, family=binomial)
summary(g4math.lr)
ps = fitted.values(g4math.lr)
strata5 = cut(ps, breaks=quantile(ps), include.lowest=TRUE, labels=FALSE)
pdf('Figures/overall.g4math.circ.psa.pdf')
psa.lr.results = circ.psa(g4math.complete$mathscore, treatment=g4math.complete$charter, strata=strata5)
dev.off()
overall.results = rbind(overall.results, data.frame(Method='Logistic Regression', Public=psa.lr.results$wtd.Mn.Public, Charter=psa.lr.results$wtd.Mn.Charter, Diff=(psa.lr.results$wtd.Mn.Charter - psa.lr.results$wtd.Mn.Public), ATE=psa.lr.results$ATE, n=psa.lr.results$df, CImin=psa.lr.results$CI.95[1], CImax=psa.lr.results$CI.95[2]))

g4math.lr.aic = stepAIC(g4math.lr, trace=FALSE)
summary(g4math.lr.aic)
ps = fitted.values(g4math.lr.aic)
strata5 = cut(ps, breaks=quantile(ps), include.lowest=TRUE, labels=FALSE)
psa.lraic.results = circ.psa(g4math.complete$mathscore, treatment=g4math.complete$charter, strata=strata5)
overall.results = rbind(overall.results, data.frame(Method='Logistic Regression Step AIC', Public=psa.lraic.results$wtd.Mn.Public, Charter=psa.lraic.results$wtd.Mn.Charter, Diff=(psa.lraic.results$wtd.Mn.Charter - psa.lraic.results$wtd.Mn.Public), ATE=psa.lraic.results$ATE, n=psa.lraic.results$df, CImin=psa.lraic.results$CI.95[1], CImax=psa.lraic.results$CI.95[2]))

g4math2 = dataCleanup(g4math)
psa.party.results = ctree(g4formula, data=g4math2)
strata = where(psa.party.results)
psa.tree.results = circ.psa(g4math2$mathscore, treatment=g4math2$charter, strata=strata)
overall.results = rbind(overall.results, data.frame(Method='Conditional Inference Trees', Public=psa.tree.results$wtd.Mn.Public, Charter=psa.tree.results$wtd.Mn.Charter, Diff=(psa.tree.results$wtd.Mn.Charter - psa.tree.results$wtd.Mn.Public), ATE=psa.tree.results$ATE, n=psa.tree.results$df, CImin=psa.tree.results$CI.95[1], CImax=psa.tree.results$CI.95[2]))
